### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Infernio** [wrye-bash/test_resources#1]
@wrye-bash/bashers I chose CC0, since this will be a pure metadata repo with no code, and the GPL isn't so great with metadata. MIT would have been another option, but there isn't much difference between the two, and CC0 might theoretically make using the resources for testing other projects easier. If you have any objections, now would be the time to voice them :)

**Comment by Utumno** [comment]
I really know nothing about all this so entirely up to you :)

I guess this might include saves and mods?

Looks you are really serious about testing which all good news - I am still rebasing so I haven't looked at the test repo yet but will do asap

**Comment by Infernio** [comment]
The test repo is probably going to get archived - seems much easier to use pytest and keep the tests inside wrye-bash, and to house the big binary blobs (saves, plugins, etc.) in a submodule (this repo).

**Comment by Infernio** [comment]
And yeah, two betas where I immediately had to make a point release to fix a serious bug has made me want testing pretty badly :P

**Comment by Utumno** [comment]
When I made that test repo the idea was that I wanted to test edit: using the game bsas - I was thinking at some point of an ini file with paths to the local tester game folders - if no path skip the tests for that game.
This is not a bad idea still methinks but I can do that.

**Comment by Utumno** [comment]
And yes always on my mind too - just the sheer amount of work... Plus setting this up - which however will give a good insight of the data model, the singletons and so on

**Comment by Utumno** [comment]
Never looked at pytest but I always felt writing unittests tough - really curious to try pytest
